// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT weather

lv_obj_t *ui_weather_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_weather;
cui_weather = lv_obj_create(comp_parent);
lv_obj_set_width( cui_weather, 94);
lv_obj_set_height( cui_weather, 73);
lv_obj_set_x( cui_weather, 0 );
lv_obj_set_y( cui_weather, 3 );
lv_obj_set_align( cui_weather, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( cui_weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_weather, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Image5;
cui_Image5 = lv_img_create(cui_weather);
lv_obj_set_width( cui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Image5, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( cui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WEATHER_NUM);
children[UI_COMP_WEATHER_WEATHER] = cui_weather;
children[UI_COMP_WEATHER_IMAGE5] = cui_Image5;
lv_obj_add_event_cb(cui_weather, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_weather, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_weather_create_hook(cui_weather);
return cui_weather; 
}

