// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void min_Animation( lv_obj_t *TargetObject, int delay);
void hour_Animation( lv_obj_t *TargetObject, int delay);
void sec_Animation( lv_obj_t *TargetObject, int delay);
void opac_Animation( lv_obj_t *TargetObject, int delay);
void sec_dot_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_ANALOG
void ui_ANALOG_screen_init(void);
void ui_event_ANALOG( lv_event_t * e);
lv_obj_t *ui_ANALOG;
lv_obj_t *ui_Backg;
lv_obj_t *ui_Date;
lv_obj_t *ui_weather_group_1;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Temp;
void ui_event_hour_group( lv_event_t * e);
lv_obj_t *ui_hour_group;
lv_obj_t *ui_hour;
lv_obj_t *ui_minute;
lv_obj_t *ui_sec;


// SCREEN: ui_DIGITAL
void ui_DIGITAL_screen_init(void);
void ui_event_DIGITAL( lv_event_t * e);
lv_obj_t *ui_DIGITAL;
lv_obj_t *ui_Image6;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_secdot;


// SCREEN: ui_MENU
void ui_MENU_screen_init(void);
void ui_event_MENU( lv_event_t * e);
lv_obj_t *ui_MENU;
void ui_event_bgmenu( lv_event_t * e);
lv_obj_t *ui_bgmenu;
void ui_event_Panel1( lv_event_t * e);
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label11;


// SCREEN: ui_SETTINGS
void ui_SETTINGS_screen_init(void);
lv_obj_t *ui_SETTINGS;
lv_obj_t *ui_Image8;
void ui_event_Panel4( lv_event_t * e);
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Label8;
void ui_event_SETTBACKLIGHT( lv_event_t * e);
lv_obj_t *ui_SETTBACKLIGHT;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label6;
lv_obj_t *ui_SETTCLOCK;
lv_obj_t *ui_Label13;
lv_obj_t *ui_CLOCK;


// SCREEN: ui_BACKLIGHT
void ui_BACKLIGHT_screen_init(void);
lv_obj_t *ui_BACKLIGHT;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Slider2;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label5;
void ui_event_Panel5( lv_event_t * e);
lv_obj_t *ui_Panel5;
void ui_event_Image7( lv_event_t * e);
lv_obj_t *ui_Image7;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label10;
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_[9] = {&ui_img_1_png, &ui_img_2_png, &ui_img_3_png, &ui_img_4_png, &ui_img_5_png, &ui_img_6_png, &ui_img_7_png, &ui_img_8_png, &ui_img_9_png};
const lv_img_dsc_t *ui_imgset_backl[1] = {&ui_img_backl1_png};
const lv_img_dsc_t *ui_imgset_bg[1] = {&ui_img_bg3_png};
const lv_img_dsc_t *ui_imgset_sm_5afad9686fe[1] = {&ui_img_sm_5afad9686fe48_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

#include <stdio.h>
#include <time.h>

///////////////////// ANIMATIONS ////////////////////
void min_Animation( lv_obj_t *TargetObject, int delay)
{
#if 0
    time_t current_time;
    struct tm *local_time;
  //  char time_buffer[6] = {0};

    // Get the current time
    current_time = time(NULL);

    // Convert to local time
    local_time = localtime(&current_time);

    // Extract hours, minutes, and seconds
    int hours = local_time->tm_hour;
    int minutes = local_time->tm_min;
    int seconds = local_time->tm_sec;

    // ANALOG
//     lv_img_set_angle(ui_sec, (3600/60)*seconds);
//     lv_img_set_angle(ui_minute, (3600/60)*minutes);
//     lv_img_set_angle(ui_hour, (3600/60)*hours);


ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 45000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, (3600/60)*minutes );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0 );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);
#endif
}
void hour_Animation( lv_obj_t *TargetObject, int delay)
{
#if 0
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 90000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
////lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);
#endif
}
void sec_Animation( lv_obj_t *TargetObject, int delay)
{
#if 0
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 15000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);
#endif
}
void opac_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void sec_dot_Animation( lv_obj_t *TargetObject, int delay)
{
#if 0
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = ui_imgset_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 12000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
//lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);
#endif
}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ANALOG( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_DIGITAL, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DIGITAL_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MENU_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      min_Animation(ui_minute, 0);
      hour_Animation(ui_hour, 0);
      sec_Animation(ui_sec, 5);
      opac_Animation(ui_weather_group_1, 0);
}
}
void ui_event_hour_group( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MENU_screen_init);
}
}
void ui_event_DIGITAL( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_MENU_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ANALOG, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_ANALOG_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      sec_dot_Animation(ui_secdot, 0);
}
}
void ui_event_MENU( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_ANALOG, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ANALOG_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_DIGITAL, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DIGITAL_screen_init);
}
}
void ui_event_bgmenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_DIGITAL, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DIGITAL_screen_init);
}
}
void ui_event_Panel1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SETTINGS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SETTINGS_screen_init);
}
}
void ui_event_Panel4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MENU_screen_init);
}
}
void ui_event_SETTBACKLIGHT( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BACKLIGHT, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BACKLIGHT_screen_init);
}
}
void ui_event_Panel5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SETTINGS, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SETTINGS_screen_init);
}
}
void ui_event_Image7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_BACKLIGHT, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_BACKLIGHT_screen_init);
}
}
void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      min_Animation(ui_minute, 0);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ANALOG_screen_init();
ui_DIGITAL_screen_init();
ui_MENU_screen_init();
ui_SETTINGS_screen_init();
ui_BACKLIGHT_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_ANALOG);
}
